---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "10 1 * * 0"

jobs:
  test:
    name: Build and test image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Test building image.
        run: podman build -t podman-ansible .

      - name: Run the built image.
        run: podman run --name test-container -d --rm podman-ansible

      - name: Verify Systemd is installed and working.
        run: systemctl status

      - name: Verify Ansible is installed and working.
        run: podman exec --tty test-container ansible local -a "hostname"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v2

      - name: Login to GitHub Contianer Registry.
        run: podman login ghcr.io -u ${{ github.repository_owner }} -p ${{ github.token }}

      - name: Build the container image.
        run: podman build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push image to GitHub Contianer Registry.
        run: podman push ghcr.io/${{ github.repository }}:latest
